### ISSUE TITLE
Augment gitignore

### ISSUE THREAD

**Issue by jmgate** [alan-turing-institute/the-turing-way-book#5]
May want to add
```
/website/.sass-cache
/website/_build
```

to the `.gitignore` file so people don't accidentally commit files generated in the midst of a local build.

**Comment by alexmorley** [comment]
For sure. There are probably a few other things that should go here too (like pycache).

**Comment by alexmorley** [comment]
For anyone who wants to take this on we need to add to our `.gitignore` some more filetypes that we would like to be ignored. See https://help.github.com/en/articles/ignoring-files for what this file does.

FYI the file to be edited is here: https://github.com/alan-turing-institute/the-turing-way-book/blob/master/.gitignore
